#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import os
from datetime import datetime
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.text import Text

console = Console()

class ReportGenerator:
    def __init__(self, domain, output_file):
        self.domain = domain
        self.output_file = output_file
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def generate_markdown(self, results):
        """Generate a markdown report"""
        md = f"# Domain Reconnaissance Report\n\n"
        md += f"**Target:** `{self.domain}`  \n"
        md += f"**Date:** {self.timestamp}  \n"
        md += f"**Generated by:** Domain - Advanced Domain Reconnaissance Tool\n\n"
        md += "---\n\n"

        # Domain Information
        if 'domain_info' in results:
            md += "## 🔍 Domain Information\n\n"
            info = results['domain_info']

            # IPs
            if 'ip_addresses' in info:
                ips = info['ip_addresses']
                md += "### IP Addresses\n"
                md += f"- **IPv4:** {', '.join(ips.get('ipv4', [])) or 'N/A'}\n"
                md += f"- **IPv6:** {', '.join(ips.get('ipv6', [])) or 'N/A'}\n\n"

            # Geolocation
            if 'geolocation' in info:
                geo = info['geolocation']
                if 'error' not in geo:
                    md += "### Geolocation\n"
                    for k, v in geo.items():
                        if v:
                            md += f"- **{k.title()}:** {v}\n"
                    md += "\n"

            # WHOIS
            if 'whois' in info:
                w = info['whois']
                if 'error' not in w:
                    md += "### WHOIS Information\n"
                    for k, v in w.items():
                        if v:
                            if isinstance(v, list):
                                v = ', '.join(str(i) for i in v[:5])
                            md += f"- **{k.replace('_', ' ').title()}:** {v}\n"
                    md += "\n"

            # DNS Records
            if 'dns_records' in info:
                dns = info['dns_records']
                if dns:
                    md += "### DNS Records\n"
                    md += "| Type | Value |\n|------|-------|\n"
                    for rtype, values in dns.items():
                        for v in values:
                            md += f"| {rtype} | `{v}` |\n"
                    md += "\n"

            # SSL Certificate
            if 'ssl' in info:
                ssl = info['ssl']
                if 'error' not in ssl:
                    md += "### SSL Certificate\n"
                    if 'issuer' in ssl:
                        issuer = ssl['issuer']
                        md += f"- **Issuer:** {issuer.get('organizationName', 'N/A')}\n"
                    md += f"- **Not After:** {ssl.get('not_after', 'N/A')}\n"
                    days = ssl.get('days_until_expiry', 'N/A')
                    expired = ssl.get('expired', False)
                    status = '⚠️ EXPIRED' if expired else ('⚠️ Expires Soon' if isinstance(days, int) and days < 30 else '✅ Valid')
                    md += f"- **Status:** {status} ({days} days remaining)\n"
                    if ssl.get('san'):
                        md += f"- **SANs:** {', '.join(ssl['san'][:10])}\n"
                    md += "\n"

            # HTTP Info
            if 'http' in info:
                http = info['http']
                md += "### HTTP Information\n"
                md += f"- **Status:** {http.get('status_code', 'N/A')}\n"
                md += f"- **Final URL:** {http.get('final_url', 'N/A')}\n"
                if http.get('technologies'):
                    md += f"- **Technologies:** {', '.join(http['technologies'])}\n"

                # Security headers
                if 'security_headers' in http:
                    md += "\n#### Security Headers\n"
                    for hdr, val in http['security_headers'].items():
                        icon = '✅' if val != 'MISSING' else '❌'
                        md += f"- {icon} **{hdr}:** {val}\n"
                md += "\n"

        # Subdomains
        if 'subdomains' in results:
            subs = results['subdomains']
            md += f"## 🌐 Subdomains ({subs.get('total', 0)} found)\n\n"
            if subs.get('subdomains'):
                md += "| Subdomain | IP Address(es) |\n|-----------|---------------|\n"
                for sub, ips in list(subs['subdomains'].items())[:50]:
                    ip_str = ', '.join(ips) if ips else 'N/A'
                    md += f"| `{sub}` | {ip_str} |\n"
                if subs['total'] > 50:
                    md += f"\n*... and {subs['total'] - 50} more (see JSON report)*\n"
            md += "\n"

        # URLs
        if 'urls' in results:
            urls = results['urls']
            md += f"## 🕷️ Discovered URLs ({urls.get('total', 0)} total)\n\n"
            categories = urls.get('categories', {})

            for cat, items in categories.items():
                if items:
                    md += f"### {cat.title()} ({len(items)})\n"
                    for item in items[:20]:
                        status = item.get('status', 0)
                        md += f"- [{status}] `{item['url']}`\n"
                    if len(items) > 20:
                        md += f"*... and {len(items) - 20} more*\n"
                    md += "\n"

        # Admin Pages
        if 'admin_pages' in results:
            admin = results['admin_pages']
            md += f"## 👑 Admin Pages ({admin.get('total', 0)} found)\n\n"
            if admin.get('pages'):
                md += "| URL | Status | Title |\n|-----|--------|-------|\n"
                for page in admin['pages']:
                    md += f"| `{page['url']}` | {page['status']} | {page.get('title', '')} |\n"
            md += "\n"

        # Attack Surface
        if 'attack_surface' in results:
            surf = results['attack_surface']
            md += "## 🎯 Attack Surface\n\n"

            if 'ports' in surf:
                ports = surf['ports']
                open_ports = ports.get('open_ports', [])
                md += f"### Open Ports ({len(open_ports)})\n"
                if open_ports:
                    md += "| Port | Service | Banner |\n|------|---------|--------|\n"
                    for p in open_ports:
                        banner = p.get('banner', '')[:60].replace('|', '-')
                        md += f"| {p['port']} | {p['service']} | {banner} |\n"
                md += "\n"

            if 'security_headers' in surf:
                hdr_data = surf['security_headers']
                score = hdr_data.get('score', 'N/A')
                md += f"### Security Headers Score: {score}\n"
                if 'headers' in hdr_data:
                    for hdr, data in hdr_data['headers'].items():
                        icon = '✅' if data['present'] else '❌'
                        val = data.get('value', 'MISSING')
                        md += f"- {icon} **{hdr}:** {val}\n"
                md += "\n"

            if 'waf_cdn' in surf:
                waf = surf['waf_cdn']
                detected = waf.get('detected', [])
                md += f"### WAF/CDN Detection\n"
                md += f"- **Detected:** {', '.join(detected) if detected else 'None detected'}\n\n"

            if 'technologies' in surf:
                techs = surf['technologies']
                md += f"### Technologies\n"
                md += f"- {', '.join(techs.get('technologies', [])) or 'Unknown'}\n\n"

        # Vulnerabilities
        if 'vulnerabilities' in results:
            vuln_data = results['vulnerabilities']
            total = vuln_data.get('total', 0)
            severity_count = vuln_data.get('severity_count', {})

            md += f"## 🔒 Vulnerabilities ({total} found)\n\n"
            md += "### Summary\n"
            md += f"| Severity | Count |\n|----------|-------|\n"
            for sev in ['Critical', 'High', 'Medium', 'Low', 'Info']:
                count = severity_count.get(sev, 0)
                md += f"| {sev} | {count} |\n"
            md += "\n"

            if vuln_data.get('vulnerabilities'):
                md += "### Vulnerability Details\n\n"
                for vuln in vuln_data['vulnerabilities']:
                    sev = vuln.get('severity', 'Info')
                    md += f"#### [{sev}] {vuln['type']}\n"
                    md += f"- **URL:** `{vuln['url']}`\n"
                    md += f"- **Details:** {vuln['detail']}\n\n"

        md += "---\n"
        md += f"*Report generated by Domain Scanner on {self.timestamp}*\n"
        md += "*⚠️ This tool is for authorized security testing only*\n"

        return md

    def generate(self, results):
        """Generate both markdown and JSON reports"""
        # Determine file paths
        base_path = os.path.splitext(self.output_file)[0]
        md_path = base_path + '.md'
        json_path = base_path + '.json'

        # Generate Markdown
        try:
            md_content = self.generate_markdown(results)
            with open(md_path, 'w', encoding='utf-8') as f:
                f.write(md_content)
            console.print(f"  [green]✓[/green] Markdown report: [bold]{md_path}[/bold]")
        except Exception as e:
            console.print(f"  [red]✗[/red] Markdown report error: {e}")

        # Generate JSON
        try:
            with open(json_path, 'w', encoding='utf-8') as f:
                json.dump({
                    'domain': self.domain,
                    'timestamp': self.timestamp,
                    'results': results
                }, f, indent=2, default=str)
            console.print(f"  [green]✓[/green] JSON report: [bold]{json_path}[/bold]")
        except Exception as e:
            console.print(f"  [red]✗[/red] JSON report error: {e}")

        # Print summary table
        self._print_summary(results)

    def _print_summary(self, results):
        """Print a visual summary"""
        table = Table(title=f"Scan Summary - {self.domain}", show_header=True, header_style="bold cyan")
        table.add_column("Module", style="cyan")
        table.add_column("Result", style="white")
        table.add_column("Status", justify="center")

        if 'domain_info' in results:
            info = results['domain_info']
            ips = info.get('ip_addresses', {}).get('ipv4', [])
            table.add_row("Domain Info", ', '.join(ips) if ips else 'N/A', "✅")

        if 'subdomains' in results:
            count = results['subdomains'].get('total', 0)
            table.add_row("Subdomains", f"{count} found", "✅" if count else "⚠️")

        if 'urls' in results:
            count = results['urls'].get('total', 0)
            table.add_row("URLs", f"{count} found", "✅" if count else "⚠️")

        if 'admin_pages' in results:
            count = results['admin_pages'].get('total', 0)
            table.add_row("Admin Pages", f"{count} found", "⚠️" if count else "✅")

        if 'attack_surface' in results:
            ports = results['attack_surface'].get('ports', {})
            count = len(ports.get('open_ports', []))
            table.add_row("Open Ports", f"{count} open", "⚠️" if count > 5 else "✅")

        if 'vulnerabilities' in results:
            vuln_data = results['vulnerabilities']
            total = vuln_data.get('total', 0)
            crit = vuln_data.get('severity_count', {}).get('Critical', 0)
            high = vuln_data.get('severity_count', {}).get('High', 0)
            status = "🔴" if crit > 0 else "🟡" if high > 0 else ("⚠️" if total > 0 else "✅")
            table.add_row("Vulnerabilities", f"{total} total ({crit} Critical, {high} High)", status)

        console.print(table)
